#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ai-b-uefi-ic
# Appelé par ai-b-ic
#
# Script d'installation en mode UEFI
# et ne fonctionne qu'avec la langue FR (fr_FR)
#
#-------------------------------------------------------------------------------

    #INSTALL BOOTLOADER {{{
    install_bootloader() {
        print_title "PROCESSUS DE BOOT - https://wiki.archlinux.org/index.php/UEFI_Bootloaders"
        print_info "Le chargeur de démarrage est responsable du chargement du noyau et du disque virtuel initial avant de lancer le processus de démarrage."
        # Achitecture du PC
        if [[ $ARCHI == i686 ]]; then
            ARCHI_REFIND="ia32"
        else
            ARCHI_REFIND="x64"
        fi
        #
        # Détermine le nom du rep d'installation de arch
        if [[ -d /boot/efi/EFI ]]; then
            number_of_arch_first=$(ls "/boot/efi/EFI/" | grep -E "arch" | awk 'length($0)<7' | wc -l)
            if [[ $number_of_arch_first -eq 0 ]]; then
                NAME_DIR_ARCHLINUX=${NAME_ARCH_FIRST}
                NUMBER_OF_ARCH=1
                IS_MULTI_BOOT_UEFI=0
            else
                digit_of_arch_after=$(( $number_of_arch_first + 1 ))
                NAME_DIR_ARCHLINUX="arch_${digit_of_arch_after}"
                NUMBER_OF_ARCH=${digit_of_arch_after}
                IS_MULTI_BOOT_UEFI=1
            fi
        else
            NAME_DIR_ARCHLINUX=${NAME_ARCH_FIRST}
            NUMBER_OF_ARCH=1
            IS_MULTI_BOOT_UEFI=0
        fi
        DIR_EFI_ARCHLINUX="/boot/efi/EFI/${NAME_DIR_ARCHLINUX}"
        print_info_cyan "Le répertoire d'installation de Arch Linux sera ${DIR_EFI_ARCHLINUX}."
        # INSCRIT NAME_DIR_ARCHLINUX DANS name_dir_archlinux.uefi pour ai-de
        echo "name_dir_archlinux=${NAME_DIR_ARCHLINUX}" > /root/name_dir_archlinux.uefi
        #
        # Choix du Manager de Boot
        if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
            print_info_cyan "Installation dans VirtualBox : le nom du Manager de Boot sera : bootx64.efi."
            MGR_EFI="boot"
            NAME_DIR_EFI="/boot/efi/EFI/BOOT"
            NAME_DIR_MGR_EFI="/EFI/BOOT/boot${ARCHI_REFIND}.efi"
        else
            print_info_cyan "Installation réelle : le nom du Manager de Boot sera refind_x64.efi."
            MGR_EFI="refind"
            NAME_DIR_EFI="/boot/efi/EFI/refind"
            NAME_DIR_MGR_EFI="/EFI/refind/refind_${ARCHI_REFIND}.efi"
        fi
        print_info_cyan "Le répertoire d'installation du Manager de Boot sera ${NAME_DIR_EFI}."
        # INSCRIT CHOIX NOM DANS name_dir_archlinux.uefi pour ai-de
        echo "name_mgr_efi=${MGR_EFI}" >> /root/name_dir_archlinux.uefi
        #
        # Installation de rEFInd
        print_info_cyan "Installation de rEFInd."
        pacman -Syu refind-efi
        # Kernels
        print_info_cyan "Copie des fichiers du kernel (EFISTUB)."
        # CREATION arch_x
        mkdir -p ${DIR_EFI_ARCHLINUX}
        cp -v /boot/vmlinuz-linux ${DIR_EFI_ARCHLINUX}/vmlinuz-${NAME_DIR_ARCHLINUX}.efi
        cp -v /boot/initramfs-linux.img ${DIR_EFI_ARCHLINUX}/initramfs-${NAME_DIR_ARCHLINUX}.img
        cp -v /boot/initramfs-linux-fallback.img ${DIR_EFI_ARCHLINUX}/initramfs-${NAME_DIR_ARCHLINUX}-fallback.img
        if [[ $IN_VIRTUAL_BOX -eq 0 ]]; then
            print_info_cyan "Copie du fichier de intel-ucode."
            cp -v /boot/intel-ucode.img ${DIR_EFI_ARCHLINUX}/intel-ucode.img
        fi
        print_info_cyan "Copie du fichier de configuration du kernel (EFISTUB)."
        cp -v /usr/share/refind/refind_linux.conf-sample ${DIR_EFI_ARCHLINUX}/refind_linux.conf
#        echo -e "\n"        
        # rEFInd : si 1ere installation
        if [[ $IS_MULTI_BOOT_UEFI -eq 0 ]]; then
            print_info_cyan "Copie des fichiers de rEFInd."
            mkdir -p ${NAME_DIR_EFI}
            cp -v /usr/share/refind/refind_${ARCHI_REFIND}.efi /boot/efi${NAME_DIR_MGR_EFI}
            cp -v /usr/share/refind/refind.conf-sample ${NAME_DIR_EFI}/refind.conf
            cp -R /usr/share/refind/icons ${NAME_DIR_EFI}/icons
#             cp -v ${NAME_DIR_EFI}/icons/os_arch.png ${NAME_DIR_EFI}/icons/os_${NAME_DIR_ARCHLINUX}.png
#             cp -v ai-fconfig/refind-icone-os_arch_ck.png ${NAME_DIR_EFI}/icons/os_${NAME_DIR_ARCHLINUX}_ck.png
            cp -v ai-fconfig/refind-icones/os_arch_${NUMBER_OF_ARCH}.png ${NAME_DIR_EFI}/icons/os_arch_${NUMBER_OF_ARCH}.png
            cp -v ai-fconfig/refind-icones/os_arch_${NUMBER_OF_ARCH}_ck.png ${NAME_DIR_EFI}/icons/os_arch_${NUMBER_OF_ARCH}_ck.png
        else
            print_info_cyan "MULTI BOOT UEFI : Pas d'installation de Manager de Boot."
            # Installe icones
#             cp -v ${NAME_DIR_EFI}/icons/os_arch.png ${NAME_DIR_EFI}/icons/os_${NAME_DIR_ARCHLINUX}.png
#             cp -v ai-fconfig/refind-icone-os_arch_ck.png ${NAME_DIR_EFI}/icons/os_${NAME_DIR_ARCHLINUX}_ck.png
            cp -v ai-fconfig/refind-icones/os_arch_${NUMBER_OF_ARCH}.png ${NAME_DIR_EFI}/icons/os_arch_${NUMBER_OF_ARCH}.png
            cp -v ai-fconfig/refind-icones/os_arch_${NUMBER_OF_ARCH}_ck.png ${NAME_DIR_EFI}/icons/os_arch_${NUMBER_OF_ARCH}_ck.png
        fi
        pause_function
    }
    #}}}
    #CONFIGURE BOOTLOADER {{{
    configure_bootloader() {
        print_title "rEFInd - https://wiki.archlinux.org/index.php/UEFI_Bootloaders#Using_rEFInd"
        print_info "rEFInd, écrit par Rod Smith, prend en charge le démarrage des noyaux EFISTUB et contient certaines caractéristiques qui leur sont propres"
        #
        # rEFInd 0.8.3 :
        # A ETUDIER
        # #scanfor internal,external,optical,manual => scanfor internal,hdbios,external,optical,manual
        # ==> Si problème CSM compatibility => à enlever
        # #uefi_deep_legacy_scan => uefi_deep_legacy_scan true
        # ==> NE PAS METTRE DANS VBOX
        if [[ $IS_MULTI_BOOT_UEFI -eq 0 ]]; then
            print_info_cyan "Configuration de refind.conf."
            sed -i "/^timeout/c\timeout 2" ${NAME_DIR_EFI}/refind.conf
            sed -i "/^#scan_all_linux_kernels/c\scan_all_linux_kernels false" ${NAME_DIR_EFI}/refind.conf
            sed -i "/^#fold_linux_kernels/c\fold_linux_kernels false" ${NAME_DIR_EFI}/refind.conf
            if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
                sed -i "/^#showtools/c\showtools shell,about,shutdown,reboot" ${NAME_DIR_EFI}/refind.conf
                sed -i "/^#dont_scan_files/c\dont_scan_files fallback.efi,shim.efi,shim-fedora.efi,gcdx64.efi,MokManager.efi" ${NAME_DIR_EFI}/refind.conf
            else
                sed -i "/^#showtools/c\showtools shell,about,shutdown,reboot,firmware" ${NAME_DIR_EFI}/refind.conf
                sed -i "/^#dont_scan_files/c\dont_scan_files BOOTX64.EFI,fallback.efi,shim.efi,shim-fedora.efi,gcdx64.efi,MokManager.efi" ${NAME_DIR_EFI}/refind.conf
                sed -i "/^#resolution 1024 768/c\resolution 1024 768" ${NAME_DIR_EFI}/refind.conf
                # PAS OK : RAJOUTES ENTRÉES DS NVRAM => PLUS DE BOOT !!!
                #sed -i "/^#scanfor/c\scanfor internal,hdbios,external,optical,manual" ${NAME_DIR_EFI}/refind.conf
                # NE SEMBLE PAS OBLIGATOIRE ( PAR DEFAUT )
                #sed -i "/^#uefi_deep_legacy_scan/c\uefi_deep_legacy_scan true" ${NAME_DIR_EFI}/refind.conf
            fi
        else
            print_info_cyan "MULTI BOOT UEFI : Pas de configuration de refind.conf."
        fi
        #
        print_info_cyan "Configuration de refind_linux.conf."
        partroot=$(echo $ROOT | sed 's/\/dev\///')
        partuuid=$(ls -l /dev/disk/by-partuuid | awk '/'$partroot'/ {print $9}')
        sed -i "/^\"Boot/d;/^$/d" ${DIR_EFI_ARCHLINUX}/refind_linux.conf
        # ROOT_FS_TYPE=ext4
        if [[ $IN_VIRTUAL_BOX -eq 1 ]]; then
            echo -e '"Boot en mode Graphique"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=graphical.target quiet initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Boot en mode Terminal"    "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=multi-user.target quiet initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Boot en mode Depannage"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=rescue.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Graphique"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=graphical.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Terminal"    "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=multi-user.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Depannage"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=rescue.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
        else
            echo -e '"Boot en mode Graphique"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap systemd.unit=graphical.target quiet initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Boot en mode Terminal"    "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap systemd.unit=multi-user.target quiet initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Boot en mode Depannage"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap systemd.unit=rescue.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Graphique"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=graphical.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Terminal"    "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=multi-user.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
            echo -e '"Fallback en mode Depannage"   "root=PARTUUID='$partuuid' rootfstype='$ROOT_FS_TYPE' rw add_efi_memmap force_addr=0xaddr systemd.unit=rescue.target initrd=EFI/'$NAME_DIR_ARCHLINUX'/intel-ucode.img initrd=EFI/'$NAME_DIR_ARCHLINUX'/initramfs-'$NAME_DIR_ARCHLINUX'-fallback.img"' >> ${DIR_EFI_ARCHLINUX}/refind_linux.conf
       fi
        #
        if [[ $IS_MULTI_BOOT_UEFI -eq 0 ]]; then
            print_info_cyan "Configuration du manager de Boot."
            # https://wiki.archlinux.org/index.php/Beginners%27_Guide#For_UEFI_motherboards 12/10/2013
            # Si /sys/firmware/efi/efivars n'est pas déjà monté.
            # Voir modifs  arch-install-scripts
            if [[ ! -d "/sys/firmware/efi/efivars" ]]; then
                mount -t efivarfs efivarfs /sys/firmware/efi/efivars
            fi
            # Supprime entrée rEFInd ArchLinux dans NVRAM si existe déjà
            _num_entree=$(efibootmgr -v | awk '/rEFInd/ {print $1}' | sed -e "s/^Boot//;s/\*$//")
            if [[ ${_num_entree} != "" ]]; then
                efibootmgr -B -b ${_num_entree}
            fi
            #
            numpartefi=$(echo $EFI_DEVICE | sed 's/\/dev\/sd[a-z]//')
            efibootmgr -c -d ${ROOT_DEVICE} -p ${numpartefi} -l ${NAME_DIR_MGR_EFI} -L "rEFInd ArchLinux"
            print_info_cyan "Vérification des entrées dans NVRAM."
            efibootmgr -v
            pause_function
        else
            print_info_cyan "MULTI BOOT UEFI : Pas de configuration du manager de Boot."
        fi
        # Installation de efistub_update.path et efistub_update.service
        print_info_cyan "Installation de efistub_update.path et efistub_update.service."
        cp -v ai-fconfig/efi-services/efistub_update.path /etc/systemd/system/efistub_update.path
        cp -v ai-fconfig/efi-services/efistub_update.service /etc/systemd/system/efistub_update.service
        sed -i "s/NAMEDIRARCHLINUX/${NAME_DIR_ARCHLINUX}/g" /etc/systemd/system/efistub_update.service
        echo -e "\n"
        systemctl enable efistub_update.path
        # SUPPRIMÉ : Voir script /home/jnd/01-scripts/Maj-refind/maj-refind
#         # Installe refind_update.path et refind_update.service
#         if [[ $IS_MULTI_BOOT_UEFI -eq 0 ]]; then
#             if [[ $MGR_EFI != "" ]]; then
#                 print_info_cyan "Installation de refind_update.service."
#                 cp -v ai-fconfig/efi-services/refind_update.path /etc/systemd/system/refind_update.path
#                 if [[ $MGR_EFI == "refind" ]]; then
#                     cp -v ai-fconfig/efi-services/ESP-refind-refind_update.service /etc/systemd/system/refind_update.service
#                 elif [[ $MGR_EFI == "boot" ]]; then
#                     cp -v ai-fconfig/efi-services/ESP-boot-refind_update.service /etc/systemd/system/refind_update.service
#                 else
#                     cp -v ai-fconfig/efi-services/ESP-microsoft-refind_update.service /etc/systemd/system/refind_update.service
#                 fi
#                 systemctl enable refind_update.path
#             fi
#         else
#             print_info_cyan "MULTI BOOT UEFI : Pas d'installation de refind_update.service."
#         fi
        # Installation de intel_ucode_update.path et intel_ucode_update.service
        if [[ $IN_VIRTUAL_BOX -eq 0 ]]; then
            print_info_cyan "Installation de intel_ucode_update.path et intel_ucode_update.service."
            cp -v ai-fconfig/efi-services/intel_ucode_update.path /etc/systemd/system/intel_ucode_update.path
            cp -v ai-fconfig/efi-services/intel_ucode_update.service /etc/systemd/system/intel_ucode_update.service
            sed -i "s/NAMEDIRARCHLINUX/${NAME_DIR_ARCHLINUX}/g" /etc/systemd/system/intel_ucode_update.service
            echo -e "\n"
            systemctl enable intel_ucode_update.path
        else
            print_info_cyan "Installation dans VirtualBox : PAS d'activion des mises à jour du microcode."
        fi
        #
        if [[ $IS_MULTI_BOOT_UEFI -eq 0 ]]; then
            print_info_cyan "Installation d'un Shell UEFI et création du script utilisé par le Shell UEFI."
            wget https://edk2.svn.sourceforge.net/svnroot/edk2/trunk/edk2/ShellBinPkg/UefiShell/X64/Shell.efi
            # OU
            # cp -v /run/archiso/bootmnt/EFI/shellx64_v2.efi /boot/efi/shellx64.efi
            cp -v Shell.efi /boot/efi/shellx64.efi
            echo "echo -on" > /boot/efi/archlinux.nsh
            if [[ $IN_VIRTUAL_BOX -eq 0 ]]; then
                echo "\EFI\arch_1\vmlinuz-arch_1.efi root=PARTUUID=$partuuid rw rootfstype=$ROOT_FS_TYPE add_efi_memmap initrd=EFI/arch_1/intel-ucode.img initrd=EFI/arch_1/initramfs-arch_1.img" >> /boot/efi/archlinux.nsh
            else
                echo "\EFI\arch_1\vmlinuz-arch_1.efi root=PARTUUID=$partuuid rw rootfstype=$ROOT_FS_TYPE add_efi_memmap initrd=EFI/arch_1/initramfs-arch_1.img" >> /boot/efi/archlinux.nsh
            fi
            print_info_cyan "Contenu du script utilisé par le Shell UEFI :"
            cat /boot/efi/archlinux.nsh
        else
            print_info_cyan "MULTI BOOT UEFI : Pas d'installation d'un Shell UEFI."
        fi
        # RAJOUT CREATION arch_x_ck VIDE
        mkdir -p ${DIR_EFI_ARCHLINUX}_ck
        pause_function
    }
    #}}}

