#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ai-b-bios-ic
# Appelé par ai-b-ic
#
# Script d'installation en mode BIOS
# Ne fonctionne qu'avec la langue FR (fr_FR)
#
# Interface graphique avec whiptail
#
#-------------------------------------------------------------------------------

    #INSTALL BOOTLOADER {{{
    install_bootloader() {
        local messages=""
        local fonction="PROCESSUS DE BOOT : CHOIX DU CHARGEUR DE DEMARRAGE.\n"
        fonction+="===================================================\n\n"
        messages="\n${fonction}"
        messages+="Sélectionner le Chargeur de Démarrage :"
        BOOTLOADER=$(whiptail --nocancel --title "${TITRE_BOX_W}" --menu "${messages}" --ok-button "Valider" 20 72 5 \
                     "GRUB" "-" \
                     "SYSLINUX" "-" \
                     "AUCUN" "-" \
                     3>&1 1>&2 2>&3)
        case "$BOOTLOADER" in
            "GRUB")
                printf '%s\n' "${BGreen}Installation de ${BYellow}grub${BGreen}...${Reset}"
                pacman -Syu grub
#               # make grub automatically detect others OS
#               pacman -Syu os-prober
                ;;
            "SYSLINUX")
                if [[ $TYPE_STORAGE_PARTITION == "GPT" ]]; then
                    printf '%s\n' "${BGreen}Installation de ${BYellow}syslinux${BGreen} et ${BYellow}gptfdisk${BGreen}...${Reset}"
                    pacman -Syu syslinux gptfdisk
                else
                    printf '%s\n' "${BGreen}Installation de ${BYellow}syslinux${BGreen}...${Reset}"
                    pacman -Syu syslinux
                fi
                ;;
        esac
        pause_function
    }
    #}}}
    #CONFIGURE BOOTLOADER {{{
    configure_bootloader() {
        local messages=""
        local fonction="CONFIGURATION DU CHARGEUR DE DEMARRAGE : "${BOOTLOADER}"\n"
        fonction+="=================================================\n\n"
        case $BOOTLOADER in
            "GRUB")
                printf '%s\n' "${BGreen}Configuration de ${BYellow}grub${BGreen}...${Reset}"
                grub-install --target=i386-pc --recheck ${ROOT_DEVICE}
                #
                messages="${fonction}"
                messages+="GRUB_TIMEOUT=3\n"
                messages+="GRUB_GFXMODE=1024x768\n"
                messages+="GRUB_DISABLE_SUBMENU=y\n"
                print_whiptail_msgbox "${messages}" "Continuer"
                sed -i "/^GRUB_TIMEOUT=/c\GRUB_TIMEOUT=3" /etc/default/grub
                sed -i "/^GRUB_GFXMODE=/c\GRUB_GFXMODE=1024x768" /etc/default/grub
                # BUGS FS#38041 FS#37904
                echo -e "\nGRUB_DISABLE_SUBMENU=y" >> /etc/default/grub
                grub-mkconfig -o /boot/grub/grub.cfg
                #
                messages="${fonction}"
                messages+="Visualiser/Editer le fichier «grub.cfg» avec «"${EDITOR}"» ?\n"
                print_whiptail_yesno "${messages}" "Editer" "Continuer"
                retour=$?
                if [[ $retour = 0 ]]; then
                    ${EDITOR} /boot/grub/grub.cfg
                fi           
                ;;
            "SYSLINUX")
                printf '%s\n' "${BGreen}Configuration de ${BYellow}syslinux${BGreen}...${Reset}"
                syslinux-install_update -i -a -m
                #
                messages="${fonction}"
                messages+="Menu Graphique au Démarrage\n"
                print_whiptail_msgbox "${messages}" "Continuer"
                cp -v /usr/lib/syslinux/bios/vesamenu.c32 /boot/syslinux/
                if [[ $IN_VIRTUAL_BOX = 0 ]]; then
                    cp -v ai-fconfig/boot-syslinux-syslinux-intel-ucode.cfg /boot/syslinux/syslinux.cfg
                else
                    cp -v ai-fconfig/boot-syslinux-syslinux.cfg /boot/syslinux/syslinux.cfg
                fi
                cp -v ai-fconfig/boot-syslinux-splash.png /boot/syslinux/splash.png
                partroot=$(echo $ROOT | sed 's/\/dev\///')
                partuuid=$(ls -l /dev/disk/by-uuid | awk '/'$partroot'/ {print $9}')
                sed -i "s/root=PART_ROOT/root=UUID=$partuuid/g" /boot/syslinux/syslinux.cfg
                #
                messages="${fonction}"
                messages+="Visualiser/Editer le fichier «syslinux.cfg» avec «"${EDITOR}"» ?\n"
                print_whiptail_yesno "${messages}" "Editer" "Continuer"
                retour=$?
                if [[ $retour = 0 ]]; then
                    ${EDITOR} /boot/syslinux/syslinux.cfg
                fi           
                ;;
        esac
        pause_function
    }
    #}}}
