#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ai-b-uefi-hc
# Appelé par ai-b
#
# Script d'installation en mode UEFI
# Ne fonctionne qu'avec la langue FR (fr_FR)
#
# Interface graphique avec dialog
#
#-------------------------------------------------------------------------------

    #CREATE PARTITION {{{
    create_partition() {
        zero_the_drive() {
            #
            # Voir : https://wiki.archlinux.org/index.php/Beginners%27_guide#Erase_partition_table
            # sgdisk --zap-all /dev/sda
            local retour=9
            local messages=""
            local titre="PARTITIONNEMENT : MISE À ZÉRO DU DISQUE «"${HDD_DEVICE}"»"
            messages="\n"
            messages+="\Zb\Z1/!\ Si Multi Boot, NE PAS METTRE À ZÉRO le disque.\Zn\n"
            messages+="\Zb\Z1/!\ TOUTES les données sur le disque sélectionné seront perdues.\Zn\n\n"
            messages+="Confirmer la mise à zéro du disque «"${HDD_DEVICE}"»\n"
            print_dialog_yesno_no "${titre}" "${messages}" "Mettre à zéro" "Annuler"
            retour=$?
            if [[ $retour = 0 ]]; then
                retour=9
                messages="\n"
                messages+="Confirmer une 2ème fois la mise à zéro du disque «"${HDD_DEVICE}"»\n"
                print_dialog_yesno_no "${titre}" "${messages}" "Mettre à zéro" "Annuler"
                retour=$?
                if [[ $retour = 0 ]]; then
                    sgdisk --zap-all ${HDD_DEVICE}
                    sync
                fi
            fi
        }
        appel_check_is_hdd_or_ssd() {
            local messages=""
            local titre="PARTITIONNEMENT : TYPE DE DISQUE"
            messages="\n"
            check_is_hdd_or_ssd "${HDD_DEVICE}"
            if [[ ${IS_HDD_OR_SSD} == "HDD" ]]; then
                messages+="\Zb\Z6!!! Le Disque «"${HDD_DEVICE}"» est un HDD.\Zn\n"
            else
                messages+="\Zb\Z6!!! Le Disque «"${HDD_DEVICE}"» est un SSD.\Zn\n"
            fi
            print_dialog_msgbox "${titre}" "${messages}" "Continuer"
        }
        select_storage_partitions() {
            local messages=""
            local titre="PARTITIONNEMENT : TABLE DE PARTITIONS"
            messages="\n"
            messages+="«cgdisk» sera lancé afin de créer les partitions sur «"${HDD_DEVICE}"»\n\n"
            messages+="\Zb\Z1/!\ Une partition EFI (ESP) de 512 Mio de type EF00\Zn\n"
            messages+="\Zb\Z1    doit être créée en 1er sur «/dev/sda».\Zn\n\n"
            messages+="\Zb\Z1/!\ Si un Multi Boot en UEFI est prévu,\Zn\n"
            messages+="\Zb\Z1    la taille de la partition EFI (ESP) devrait être de 1024 Mio.\Zn\n"
            print_dialog_msgbox "${titre}" "${messages}" "Continuer"
            TYPE_STORAGE_PARTITION="GPT"
         }
        select_hdd_devices() {
            local messages=""
            local titre="PARTITIONNEMENT : SÉLECTION DU DISQUE À PARTITIONNER"
            messages="\n"
            local liste_disque_present=$(LC_ALL=C parted -sl 2> /dev/null | grep -E 'Mod|/dev/sd[a-z]' | sed -e "s/\(^Disk.*\)/\1\n/;s/Model/\\\nModèle/;s/Disk/Disque/")
            messages+="Liste des Disques présents dans le PC :\n"
            messages+="---------------------------------------"
            messages+=${liste_disque_present}"\n\n"
            messages+="Sélectionner le Disque à partitionner :"
            local hauteur=0
            local nb_hdd=$(LC_ALL=C parted -sl 2> /dev/null | grep "/dev/sd[a-z]" | wc -l)
            case "$nb_hdd" in
                [1-2])  hauteur=25 ;;
                3)  hauteur=30 ;;
                4)  hauteur=35 ;;
                *)  hauteur=40 ;;
            esac
            local liste_hdd_devices=$(LC_ALL=C parted -sl 2> /dev/null | grep "/dev/sd[a-z]" | sed -e "s/://" | awk '{print $2   " "   $3$4}')
            HDD_DEVICE=$(dialog --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --menu "${messages}" $hauteur 72 6 ${liste_hdd_devices} 3>&1 1>&2 2>&3)
        }
        select_hdd_devices
        #
        appel_check_is_hdd_or_ssd
        #
        zero_the_drive
        #
        select_storage_partitions
        #
        cgdisk $HDD_DEVICE
    }
    #}}}
    #FORMAT DEVICE {{{
    format_device() {
        local messages=""
        local titre=""
        local retour=9
        select_filesystem() {
        # "ext4" "btrfs" "reiserfs" "ntfs" "vfat" "ext2" "ext3" "jfs" "xfs"
            TYPE="ext4"
        }
#         umount_partition() {
#             #check if swap is on and umount
#             swapon -s | grep $1 && swapoff $1
#             #check if partition is mounted and umount
#             mount | grep $1 && umount $1
#         }
        format_partition() {
            printf '%s\n' "${BGreen}Formatage de la partition ${BYellow}$1${BGreen}...${Reset}"
#            umount_partition "$1"
            [[ -z $3 ]] && select_filesystem
            if [[ $1 == $ROOT ]]; then
                ROOT_FS_TYPE=$TYPE
            fi
            mkfs.$TYPE $1
            fsck $1
            tune2fs -c 30 $1
            mkdir -p $2
            mount -t $TYPE $1 $2
        }
        format_efi_partition() {
            titre="PARTITIONNEMENT : FORMATAGE DE LA PARTITION «ESP»"
            messages="\n"
            messages+="\Zb\Z6!!! Si Multi Boot en UEFI, NE PAS FORMATER la partition «ESP».\Zn\n\n"
            messages+="\Zb\Z1/!\ Si la partition est formatée,\Zn\n"
            messages+="\Zb\Z1    Toutes les données sur la partition choisie seront perdues.\Zn\n\n"
            messages+="Confirmer le formatage de la partition ESP «"$1"»\n"
            print_dialog_yesno_no "${titre}" "${messages}" "Formater" "Annuler"
            retour=$?
            if [[ $retour = 0 ]]; then
                printf '%s\n' "${BGreen}Formatage de la partition ESP ${BYellow}$1${BGreen}...${Reset}"
#                umount_partition "$1"
                mkfs.vfat -F32 $1
                fsck $1
                mkdir -p $2
                mount -t vfat $1 $2
            else
#                umount_partition "$1"
                fsck $1
                mkdir -p $2
                mount -t vfat $1 $2
            fi
        }
        format_swap_partition() {
            titre="PARTITIONNEMENT : FORMATAGE DE LA PARTITION «SWAP»"
            messages="\n"
            messages+="\Zb\Z6!!! Si Multi Boot, NE PAS FORMATER la partition «SWAP».\Zn\n\n"
            messages+="Confirmer le formatage de la partition SWAP «"$1"»\n"
            print_dialog_yesno_no "${titre}" "${messages}" "Formater" "Annuler"
            retour=$?
            if [[ $retour = 0 ]]; then
                printf '%s\n' "${BGreen}Formatage de la partition SWAP ${BYellow}$1${BGreen}...${Reset}"
#                umount_partition "$1"
                mkswap $1
                swapon $1
            else
#                umount_partition "$1"
                swapon $1
            fi
        }

# EN UEFI : 1ère partition = EF00 UEFI SYSTEM_PARTITION
        partitions=$(LC_ALL=C fdisk -l $HDD_DEVICE | sed -e "s/*//" | awk '{print $1"  "$5}' | grep "/dev/")
# CHOIX PARTITION ROOT OBLIGATOIRE
        titre="PARTITIONNEMENT : SÉLECTION PARTITION «ROOT»"
        messages="\n"
        messages+="\Zb\Z1/!\ Toutes les données sur la partition choisie seront perdues.\Zn\n"
        ROOT=$(dialog --colors --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --menu "${messages}" 20 72 8 ${partitions} 3>&1 1>&2 2>&3)
        ROOT_DEVICE=$(echo $ROOT | sed 's/[0-9]//')
        format_partition "$ROOT" "${MOUNTPOINT}"
        CHOIX_PARTITIONS+=$(echo $ROOT)" = /root.  "
# CHOIX PARTITION ESP OBLIGATOIRE
        titre="PARTITIONNEMENT : SÉLECTION PARTITION «ESP»"
        messages="\n"
        messages+=${CHOIX_PARTITIONS}"\n\n"
        partitions=$(LC_ALL=C fdisk -l $HDD_DEVICE | grep -v $ROOT | sed -e "s/*//" | awk '{print $1"  "$5}' | grep "/dev/")
        EFI_DEVICE=$(dialog --colors --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --menu "${messages}" 20 72 8 ${partitions} 3>&1 1>&2 2>&3)
        format_efi_partition "$EFI_DEVICE" "${MOUNTPOINT}/boot/efi"
        CHOIX_PARTITIONS+=$(echo $EFI_DEVICE)" = /boot/efi.  "
# CHOIX PARTITION SWAP FACULTATIF
        titre="PARTITIONNEMENT : SÉLECTION PARTITION «SWAP»"
        messages="\n"
        messages+="\Zb\Z6!!! LA PARTITION «SWAP» EST FACULTATIVE.\Zn\n\n"
        messages+=${CHOIX_PARTITIONS}"\n\n"
        partitions=$(LC_ALL=C fdisk -l $HDD_DEVICE | grep -v $ROOT | grep -v $EFI_DEVICE | sed -e "s/*//" | awk '{print $1"  "$5}' | grep "/dev/")
        L_SWAP=$(dialog --colors --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --cancel-label "Annuler" --menu "${messages}" 20 72 8 ${partitions} 3>&1 1>&2 2>&3)
        retour=$?
        if [[ $retour = 0 ]]; then
            format_swap_partition "$L_SWAP"
            CHOIX_PARTITIONS+=$(echo $L_SWAP)" = /swap.\n"
        else
            L_SWAP="/dev/sda98"
        fi
# CHOIX PARTITION HOME FACULTATIF
        titre="PARTITIONNEMENT : SÉLECTION PARTITION «HOME»"
        messages="\n"
        messages+="\Zb\Z6!!! LA PARTITION «HOME» EST FACULTATIVE.\Zn\n\n"
        messages+="\Zb\Z1/!\ Toutes les données sur la partition choisie seront perdues.\Zn\n\n"
        messages+=${CHOIX_PARTITIONS}"\n\n"
        partitions=$(LC_ALL=C fdisk -l $HDD_DEVICE | grep -v $ROOT | grep -v $EFI_DEVICE | grep -v $L_SWAP | sed -e "s/*//" | awk '{print $1"  "$5}' | grep "/dev/")
        L_HOME=$(dialog --colors --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --cancel-label "Annuler" --menu "${messages}" 20 72 8 ${partitions} 3>&1 1>&2 2>&3)
        retour=$?
        if [[ $retour = 0 ]]; then
            format_partition "$L_HOME" "${MOUNTPOINT}/home"
            CHOIX_PARTITIONS+=$(echo $L_HOME)" = /home."
        else
            L_HOME="/dev/sda99"
        fi
    }
    #}}}
