#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ai-b-bios-ic
# Appele par ai-b-ic
#
# Script d'installation en mode BIOS
# Ne fonctionne qu'avec la langue FR (fr_FR)
#
# Interface graphique avec dialog
#
#-------------------------------------------------------------------------------

    #INSTALL BOOTLOADER {{{
    install_bootloader() {
        local messages=""
        local titre="PROCESSUS DE BOOT : CHOIX DU CHARGEUR DE DEMARRAGE"
        messages="\n"
        messages+="Selectionner le Chargeur de Demarrage :"
        BOOTLOADER=$(dialog --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Selectionner" --menu "${messages}" 20 72 5 \
                     "GRUB" "" \
                     "SYSLINUX" "" \
                     "AUCUN" "" \
                     3>&1 1>&2 2>&3)
        case "$BOOTLOADER" in
            "GRUB")
                printf '%s\n' "${BGreen}Installation de ${BYellow}grub${BGreen}...${Reset}"
                pacman -Syu grub
#               # make grub automatically detect others OS
#               pacman -Syu os-prober
                ;;
            "SYSLINUX")
                if [[ $TYPE_STORAGE_PARTITION == "GPT" ]]; then
                    printf '%s\n' "${BGreen}Installation de ${BYellow}syslinux${BGreen} et ${BYellow}gptfdisk${BGreen}...${Reset}"
                    pacman -Syu syslinux gptfdisk
                else
                    printf '%s\n' "${BGreen}Installation de ${BYellow}syslinux${BGreen}...${Reset}"
                    pacman -Syu syslinux
                fi
                ;;
        esac
        pause_function
    }
    #}}}
    #CONFIGURE BOOTLOADER {{{
    configure_bootloader() {
        local messages=""
        local titre="CONFIGURATION DU CHARGEUR DE DEMARRAGE : ${BOOTLOADER}"
        case $BOOTLOADER in
            "GRUB")
                printf '%s\n' "${BGreen}Configuration de ${BYellow}grub${BGreen}...${Reset}"
                grub-install --target=i386-pc --recheck ${ROOT_DEVICE}
                #
                messages="\n"
                messages+="GRUB_TIMEOUT=3\n"
                messages+="GRUB_GFXMODE=1024x768\n"
                messages+="GRUB_DISABLE_SUBMENU=y\n"
                print_dialog_msgbox "${titre}" "${messages}" "Continuer"
                sed -i "/^GRUB_TIMEOUT=/c\GRUB_TIMEOUT=3" /etc/default/grub
                sed -i "/^GRUB_GFXMODE=/c\GRUB_GFXMODE=1024x768" /etc/default/grub
                # BUGS FS#38041 FS#37904
                echo -e "\nGRUB_DISABLE_SUBMENU=y" >> /etc/default/grub
                printf '%s\n' "${BGreen}Configuration de ${BYellow}grub.cfg${BGreen}...${Reset}"
                grub-mkconfig -o /boot/grub/grub.cfg
                #
                messages="\n"
                messages+="Visualiser/Editer le fichier ${Byellow_dlg}grub.cfg${Reset_dlg} avec ${BRwhite_dlg}${EDITOR}${Reset_dlg} ?\n"
                print_dialog_yesno "${titre}" "${messages}" "Editer" "Continuer"
                retour=$?
                if [[ $retour = 0 ]]; then
                    ${EDITOR} /boot/grub/grub.cfg
                fi           
                ;;
            "SYSLINUX")
                printf '%s\n' "${BGreen}Configuration de ${BYellow}syslinux${BGreen}...${Reset}"
                syslinux-install_update -i -a -m
                #
                messages="\n"
                messages+="Menu Graphique au Demarrage\n"
                print_dialog_msgbox "${titre}" "${messages}" "Continuer"
                printf '%s\n' "${BGreen}Configuration de ${BYellow}syslinux.cfg${BGreen}...${Reset}"
                cp -v /usr/lib/syslinux/bios/vesamenu.c32 /boot/syslinux/
                if [[ $IN_VIRTUAL_BOX = 0 ]]; then
                    cp -v ai-fconfig/boot-syslinux-syslinux-intel-ucode.cfg /boot/syslinux/syslinux.cfg
                else
                    cp -v ai-fconfig/boot-syslinux-syslinux.cfg /boot/syslinux/syslinux.cfg
                fi
                cp -v ai-fconfig/boot-syslinux-splash.png /boot/syslinux/splash.png
                partroot=$(echo $ROOT | sed 's/\/dev\///')
                partuuid=$(ls -l /dev/disk/by-uuid | awk '/'$partroot'/ {print $9}')
                sed -i "s/root=PART_ROOT/root=UUID=$partuuid/g" /boot/syslinux/syslinux.cfg
                #
                messages="\n"
                messages+="Visualiser/Editer le fichier ${Byellow_dlg}syslinux.cfg${Reset_dlg} avec ${BRwhite_dlg}${EDITOR}${Reset_dlg} ?\n"
                print_dialog_yesno "${titre}" "${messages}" "Editer" "Continuer"
                retour=$?
                if [[ $retour = 0 ]]; then
                    ${EDITOR} /boot/syslinux/syslinux.cfg
                fi           
                ;;
        esac
        pause_function
    }
    #}}}
