#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# ai-b
#
# HORS CHROOT
#
# Ne fonctionne qu'avec la langue FR (fr_FR)
#
# Interface graphique avec dialog
#
# Run this script after your first boot with archlinux-AAAA.MM.JJ-dual.iso (as root)

source $(pwd)/ai-commons

    #CONFIGURE KEYMAP {{{
    configure_keymap() {
        local messages=""        
        local titre="SÉLECTION DU TYPE DE CLAVIER"
        messages="\n"
        messages+="Sélectionner le type de clavier (AZERTY ou BÉPO) :"
        REPLY=$(dialog --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --menu "${messages}" 16 72 5 \
                "AZERTY" "" \
                "BÉPO" "" \
                3>&1 1>&2 2>&3)
        case "$REPLY" in
            "AZERTY")
                KEYMAP=fr-latin9
                TYPE_KEYBOARD="AZERTY"
                ;;
            "BÉPO")
                KEYMAP=fr-bepo-latin9
                TYPE_KEYBOARD="BEPO"
                ;;
        esac
        messages="\n"
        messages+="Type de clavier  : "${TYPE_KEYBOARD}"\n"
        messages+="Valeur de KEYMAP : "${KEYMAP}"\n"
        print_dialog_msgbox "${titre}" "${messages}" "Continuer"
        loadkeys $KEYMAP
#        setfont Lat2-Terminus16
        setfont lat9w-16
    }
    #}}}
    #
    # create_partition et format_device : ai-b-bios-hc ou ai-b-uefi-hc
    #
    #}}}
    #CONFIGURE MIRRORLIST {{{
    configure_mirrorlist() {
        local messages=""
        local titre="CONFIGURATION DU FICHIER «/etc/pacman.d/mirrorlist»"
        local retour=9
        local date_du_jour=$(date +%Y-%m-%d)
        local url="https://www.archlinux.org/mirrorlist/?country=FR&use_mirror_status=on"
        local tmpfile=$(mktemp --suffix=-mirrorlist)
        # Get latest mirror list and save to tmpfile
        printf '%s\n' "${BGreen}Récupération des serveurs ${BYellow}FR${BGreen}...${Reset}"
        curl -so ${tmpfile} ${url}
        # Backup and replace current mirrorlist file (if new file is non-zero)
        if [[ -s ${tmpfile} ]]; then
            date_Generated=$(cat "${tmpfile}" | awk '/Generated/ {print $4}')
            if [[ ${date_Generated} == ${date_du_jour} ]]; then
                sed -i "s/^#Server/Server/g" ${tmpfile}
                sed -i "/^## Score/d" ${tmpfile}
                mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.original
                mv ${tmpfile} /etc/pacman.d/mirrorlist
                chmod +r /etc/pacman.d/mirrorlist
                retour=0
            else
                retour=1
            fi
        else
            retour=1
        fi
        # Fin ou Erreur
        if [[ $retour = 0 ]]; then
            messages="\n"
            messages+="Succès de la configuration du fichier «/etc/pacman.d/mirrorlist».\n\n"
            messages+="Visualiser/Éditer le fichier «mirrorlist» avec «"${EDITOR}"» ?\n"
            print_dialog_yesno "${titre}" "${messages}" "Éditer" "Continuer"
            retour=$?
            if [[ $retour = 0 ]]; then
                ${EDITOR} /etc/pacman.d/mirrorlist
            fi           
        else
            messages="\n"
            messages+="Échec de la configuration du fichier «/etc/pacman.d/mirrorlist».\n\n"
            messages+="Edition manuelle du fichier mirrorlist avec "${EDITOR}"\n"
            print_dialog_msgbox "${titre}" "${messages}" "Éditer"
            mv /etc/pacman.d/mirrorlist.original /etc/pacman.d/mirrorlist
            chmod +r /etc/pacman.d/mirrorlist
            ${EDITOR} /etc/pacman.d/mirrorlist
        fi
    }
    #}}}
    #INSTALL BASE SYSTEM {{{
    install_base_system() {
        local retour=9
        local liste_paquets=""
        local messages=""
        local titre="INSTALLATION DU SYSTÈME DE BASE"
        messages="\n"
        messages+="En utilisant le script «pacstrap», seront installés :\n"
        if [[ $IS_UEFI = 1 ]]; then
            messages+="le système de base, gptfdisk, wget"
            liste_paquets="base dialog lz4 gptfdisk elinks wget"
        else
            messages+="le système de base, wget"
            liste_paquets="base dialog lz4 elinks wget"
        fi
        # Intel Microcode
        if [[ $IN_VIRTUAL_BOX = 0 ]]; then
            messages+=", elinks et intel-ucode.\n"
            liste_paquets+=" intel-ucode"
        else
            messages+=" et elinks.\n\n"
            messages+="${BRcyan_dlg}!!!${Reset_dlg} Installation dans Oracle VM VirtualBox :\n"
            messages+="    PAS d'intallation des mises à jour du microcode.\n"
        fi        
        print_dialog_msgbox "${titre}" "${messages}" "Continuer"
        printf '%s\n' "${BGreen}Installation du système de base...${Reset}"
        pacstrap ${MOUNTPOINT} ${liste_paquets}
        retour=$?
        if [[ $retour = 1 ]]; then
            messages="\n"
            messages+="${BRred_dlg}/!\ ERREUR${Reset_dlg}\n"
            messages+="    Erreur durant l'éxécution du script «pacstrap».\n"
            messages+="    ARRÊT immédiat.\n"
            print_dialog_msgbox "${titre}" "${messages}" "OK"
            exit 1
        fi
        # Si WiFi : installe les outils nécessaires
        local name_net_wireless=$(ip link | awk '/wlp/ {print $2}' | sed -e "s/://")
        if [[ -n ${name_net_wireless} ]]; then
            messages="\n"
            messages+="En utilisant le script «pacstrap»,\n"
            messages+="Installe les outils nécessaires pour le WiFi\n"
            print_dialog_msgbox "${titre}" "${messages}" "Continuer"
            printf '%s\n' "${BGreen}Installation des outils pour le WiFi...${Reset}"
            pacstrap ${MOUNTPOINT} iw wireless_tools wpa_actiond wpa_supplicant dialog
            retour=$?
            if [[ $retour = 1 ]]; then
                messages="\n"
                messages+="${BRred_dlg}/!\ ERREUR${Reset_dlg}\n"
                messages+="    Erreur durant l'éxécution du script «pacstrap».\n"
                messages+="    ARRÊT immédiat.\n"
                print_dialog_msgbox "${titre}" "${messages}" "OK"
                exit 1
            fi
        fi
        pause_function
    }
    #}}}
    #CONFIGURE FSTAB {{{
    genere_fstab() {
        local retour=9
        local messages=""
        local titre="GÉNÉRATION DU FICHIER «/etc/fstab» AVEC UUID"
        messages="\n"
        genfstab -U -p ${MOUNTPOINT} >> ${MOUNTPOINT}/etc/fstab
        messages+="Visualiser le fichier «/etc/fstab» ?\n"
        print_dialog_yesno "${titre}" "${messages}" "Visualiser" "Continuer"
        retour=$?
        if [[ $retour = 0 ]]; then
            cat ${MOUNTPOINT}/etc/fstab
            pause_function
        fi           
    }
    #}}}
    # ECRITURE DES VARIABLES {{{
    write_variables_ali() {
        touch ${MOUNTPOINT}/root/variables.ali
        echo "TYPE_KEYBOARD=${TYPE_KEYBOARD}" >> ${MOUNTPOINT}/root/variables.ali
        local name_net_wired=$(ip link | awk '/enp/ {print $2}' | sed -e "s/://")
        echo "NAME_NET_WIRED=${name_net_wired}" >> ${MOUNTPOINT}/root/variables.ali
        echo "IS_UEFI=${IS_UEFI}" >> ${MOUNTPOINT}/root/variables.ali
        echo "IN_VIRTUAL_BOX=${IN_VIRTUAL_BOX}" >> ${MOUNTPOINT}/root/variables.ali
        echo "IS_HDD_OR_SSD=${IS_HDD_OR_SSD}" >> ${MOUNTPOINT}/root/variables.ali
        echo "TYPE_STORAGE_PARTITION=${TYPE_STORAGE_PARTITION}" >> ${MOUNTPOINT}/root/variables.ali
        echo "ROOT_DEVICE=${ROOT_DEVICE}" >> ${MOUNTPOINT}/root/variables.ali
        echo "ROOT=${ROOT}" >> ${MOUNTPOINT}/root/variables.ali
        echo "ROOT_FS_TYPE=${ROOT_FS_TYPE}" >> ${MOUNTPOINT}/root/variables.ali
        echo "IS_VAR_SEPARATE=${IS_VAR_SEPARATE}" >> ${MOUNTPOINT}/root/variables.ali
        echo "EFI_DEVICE=${EFI_DEVICE}" >> ${MOUNTPOINT}/root/variables.ali
        #
#        echo -e "\nVérification du fichier ${MOUNTPOINT}/root/variables.ali avec $EDITOR"
#        pause_function
#        $EDITOR ${MOUNTPOINT}/root/variables.ali
    }
    #}}}
    #UMOUNT PARTITIONS {{{
    umount_partitions(){
        mounted_partitions=($(lsblk | grep ${MOUNTPOINT} | awk '{print $7}' | sort -r))
        swapoff -a
        for i in ${mounted_partitions[@]}; do
            umount $i
        done
    }
    #}}}

    #FINISH {{{
    finish() {
        local messages=""        
        local titre="PARTIE 3 : INSTALLATION TERMINÉE"
        messages="\n"
        messages+="Une copie de «AI» sera placé\n"
        messages+="dans le répertoire /root du nouveau système.\n\n"
        messages+="Copie des fichiers de configuration\n"
        messages+="dans le répertoire /root du nouveau système.\n\n"
        print_dialog_msgbox "${titre}" "${messages}" "Copier"
        # COPY AI TO ROOT FOLDER IN THE NEW SYSTEM
        printf '%s\n' "${BGreen}Copie de «${BYellow}AI${BGreen}» dans le répertoire «${BYellow}/root${BGreen}» du nouveau système...${Reset}"
        cp -R $(pwd) ${MOUNTPOINT}/root
        # COPY ROOT FILES TO ROOT FOLDER IN THE NEW SYSTEM
        printf '%s\n' "${BGreen}Copie des fichiers de configuration de «${BYellow}bash${BGreen}» dans le répertoire «${BYellow}/root${BGreen}» du nouveau système...${Reset}"
        cp -v ai-fconfig/root-.bashrc ${MOUNTPOINT}/root/.bashrc
        cp -v ai-fconfig/root-.bash_profile ${MOUNTPOINT}/root/.bash_profile
        pause_function
        #
        messages="\n"
        messages+="Fermer tous les terminaux ouverts (TTY 2, ...).\n"
        print_dialog_msgbox "${titre}" "${messages}" "Continuer"
        # umount mounted partitions
        umount_partitions
        # Redémarrer ou Éteindre
        messages="\n"
        # Si dans VirtualBox
        if [[ $IN_VIRTUAL_BOX = 1 ]]; then
            messages+="Dans VirtualBox : choisir ÉTEINDRE,\n"
            messages+="Modifier l'ordre de démarrage dans Système,\n"
            messages+="Enlever ISO dans Stokage et relancer la VM.\n\n"
        else
            messages+="Sur PC Réel : choisir REDÉMARRER,\n"
            messages+="Modifier l'ordre de démarrage dans UEFI/BIOS,\n"
            messages+="Enlever la clé USB ou le CD et redémarrer.\n\n"        
        fi
        messages+="Sélectionner l'arrêt (Redémarrer ou Éteindre) :"
        REPLY=$(dialog --nocancel --backtitle "${TITRE_BOX_W}" --title "${titre}" --ok-label "Sélectionner" --menu "${messages}" 20 72 5 \
                "REDÉMARRER" "" \
                "ÉTEINDRE" "" \
                3>&1 1>&2 2>&3)
        case "$REPLY" in
            "REDÉMARRER")
                reboot
                ;;
            "ÉTEINDRE")
                poweroff
                ;;
        esac
    }
    #}}}

# ARCHLINUX INSTALL SCRIPTS - https://github.com/jeannoeldot/alid/ai-b
# TEST SI AI-B DELA LANCE : NON => EXECUTE AI-B. OUI => EXECUTE AI-B3 (FIN)
if [[ -f /root/ai-b.launched ]]; then
    # PARTIE 3 HORS CHROOT
    #
    # Installation dans VirtualBox ou réelle
    check_is_in_virtualbox
    # Sets the interval of inactivity et fonts
    setterm -blank 0
#     setfont Lat2-Terminus16
    setfont lat9w-16
    #
    finish
else
    # PARTIE 1 HORS CHROOT
    #
    # Sets the interval of inactivity
    setterm -blank 0
    titre="INSTALLATION PARTIE 1 HORS CHROOT"
    messages="\n"
    # Editeur par défaut
    messages+="L'éditeur par défaut est : nano\n"
    # UEFI ou BIOS
    check_is_uefi_or_bios
    if [[ $IS_UEFI = 1 ]]; then
        messages+="Installation en mode     : UEFI\n"
        source $(pwd)/ai-b-uefi-hc
    else
        messages+="Installation en mode     : BIOS\n"
        source $(pwd)/ai-b-bios-hc
    fi
    # Installation dans VirtualBox ou réelle
    check_is_in_virtualbox
    if [[ $IN_VIRTUAL_BOX = 1 ]]; then
        messages+="Installation dans        : Oracle VM VirtualBox\n"
    else
        messages+="Installation dans        : PC Réel\n"
    fi    
    print_dialog_msgbox "${titre}" "${messages}" "Continuer"
    #
    configure_keymap
    # ai-b-bios-hc ou ai-b-uefi-hc
    create_partition
    format_device
    #
    configure_mirrorlist
    install_base_system
    genere_fstab
    #
    titre="FIN INSTALLATION PARTIE 1 HORS CHROOT"
    messages="\n"
    # COPIE AI TO ROOT FOLDER IN THE NEW SYSTEM
    cp -R $(pwd) ${MOUNTPOINT}/root
    cp -f ${MOUNTPOINT}/root/ai/ai-b-ic ${MOUNTPOINT}/root/ai/ai-b
    #
    write_variables_ali
    #
    messages+="Commandes à éxécuter dans l'ordre pour poursuivre l'installation :\n\n"
    messages+="${Byellow_dlg}cd && arch-chroot /mnt /bin/bash => Chroot dans le nouveau système${Reset_dlg}\n"
    messages+="${Byellow_dlg}cd /root/ai && ./ai-b            => Partie 2 de l'installation${Reset_dlg}\n"
    print_dialog_msgbox "${titre}" "${messages}" "Continuer"
    #
    echo "ai-b_launched=1" > /root/ai-b.launched
    exit 0
fi

