#!/usr/bin/env bash
case $1 in
	civ4) env WINEPREFIX=/home/jnd/.wine wine "/home/jnd/.wine/drive_c/Program Files/2K Games/Firaxis Games/Sid Meier's Civilization 4 Complete/Civilization4.exe"
			;;
	civ4_bts) env WINEPREFIX=/home/jnd/.wine wine "/home/jnd/.wine/drive_c/Program Files/2K Games/Firaxis Games/Sid Meier's Civilization 4 Complete/Beyond the Sword/Civ4BeyondSword.exe"
			;;
	civ4_w) env WINEPREFIX=/home/jnd/.wine wine "/home/jnd/.wine/drive_c/Program Files/2K Games/Firaxis Games/Sid Meier's Civilization 4 Complete/Warlords/Civ4Warlords.exe"
			;;
	civ4_c) env WINEPREFIX=/home/jnd/.wine wine "/home/jnd/.wine/drive_c/Program Files/2K Games/Firaxis Games/Sid Meier's Civilization IV Colonization/Colonization.exe"
			;;
esac

exit 0
